Puntmig\Search\Event\Event:
    type: entity
    repositoryClass: Puntmig\Search\Server\Doctrine\DoctrineEventRepository
    table: event
    id:
        id:
            type: integer
            generator:
                strategy: AUTO

    fields:
        consistencyHash:
            column: consistency_hash
            type: string
            length: 255
            nullable: false
        name:
            column: name
            type: string
            length: 255
            nullable: false
        key:
            column: engonga_key
            type: string
            length: 255
            nullable: false
        payload:
            column: payload
            type: text
            nullable: false
        occurredOn:
            column: occurred_on
            type: integer
            nullable: false
