services:

    #
    # Console commands
    #
    apisearch_server.command_with_command_bus_and_god_token:
        class: Apisearch\Server\Console\CommandWithBusAndGodToken
        abstract: true
        arguments:
            - "@apisearch_server.command_bus"
            - "%apisearch_server.god_token%"

    apisearch_server.command_with_query_bus_and_god_token:
        class: Apisearch\Server\Console\CommandWithBusAndGodToken
        abstract: true
        arguments:
            - "@apisearch_server.query_bus"
            - "%apisearch_server.god_token%"

    apisearch_server.configure_environment_command:
        class: Apisearch\Server\Console\ConfigureEnvironmentCommand
        parent: apisearch_server.command_with_command_bus_and_god_token
        tags:
            -  { name: console.command, command: apisearch-server:configure-environment }

    apisearch_server.clean_environment_command:
        class: Apisearch\Server\Console\CleanEnvironmentCommand
        parent: apisearch_server.command_with_command_bus_and_god_token
        tags:
            -  { name: console.command, command: apisearch-server:clean-environment }

    apisearch_server.create_index_command:
        class: Apisearch\Server\Console\CreateIndexCommand
        parent: apisearch_server.command_with_command_bus_and_god_token
        tags:
            -  { name: console.command, command: apisearch-server:create-index }

    apisearch_server.delete_index_command:
        class: Apisearch\Server\Console\DeleteIndexCommand
        parent: apisearch_server.command_with_command_bus_and_god_token
        tags:
            -  { name: console.command, command: apisearch-server:delete-index }

    apisearch_server.check_index_command:
        class: Apisearch\Server\Console\CheckIndexCommand
        parent: apisearch_server.command_with_query_bus_and_god_token
        tags:
            -  { name: console.command, command: apisearch-server:check-index }

    apisearch_server.add_token_command:
        class: Apisearch\Server\Console\AddTokenCommand
        parent: apisearch_server.command_with_command_bus_and_god_token
        tags:
            -  { name: console.command, command: apisearch-server:add-token }

    apisearch_server.delete_token_command:
        class: Apisearch\Server\Console\DeleteTokenCommand
        parent: apisearch_server.command_with_command_bus_and_god_token
        tags:
            -  { name: console.command, command: apisearch-server:delete-token }

    apisearch_server.delete_all_tokens_command:
        class: Apisearch\Server\Console\DeleteTokensCommand
        parent: apisearch_server.command_with_command_bus_and_god_token
        tags:
            -  { name: console.command, command: apisearch-server:delete-all-tokens }

    apisearch_server.generate_basic_tokens_command:
        class: Apisearch\Server\Console\GenerateBasicTokensCommand
        parent: apisearch_server.command_with_command_bus_and_god_token
        tags:
            -  { name: console.command, command: apisearch-server:generate-basic-tokens }

    apisearch_server.print_tokens_command:
        class: Apisearch\Server\Console\PrintTokensCommand
        parent: apisearch_server.command_with_query_bus_and_god_token
        tags:
            -  { name: console.command, command: apisearch-server:print-tokens }

    apisearch_server.configuration:
        class: Apisearch\Server\Console\ServerConfigurationCommand
        arguments:
            - "@kernel"
        tags:
            -  { name: console.command, command: apisearch-server:server-configuration }

    #
    # Consumer workers
    #
    apisearch_server.event_store_consumer:
        class: Apisearch\Server\Console\EventStoreConsumer
        arguments:
            - "@rs_queue.consumer"
            - "@apisearch_server.event_publisher"
            - "@rs_queue.publisher"
        tags:
            -  { name: console.command, command: apisearch-worker:domain-events-consumer }

    apisearch_server.logs_consumer:
        class: Apisearch\Server\Console\LogsConsumer
        arguments:
            - "@rs_queue.consumer"
            - "@apisearch.log_repository_main.default"
            - "@rs_queue.publisher"
        tags:
            -  { name: console.command, command: apisearch-worker:logs-consumer }

    apisearch_server.command_consumer:
        class: Apisearch\Server\Console\CommandsConsumer
        arguments:
            - "@rs_queue.consumer"
            - "@apisearch_server.command_bus.inline"
        tags:
            -  { name: console.command, command: apisearch-worker:command-consumer }