services:

    #
    # Console commands
    #
    apisearch.server.event_store_consumer:
        class: Apisearch\Server\Console\EventStoreConsumer
        arguments:
            - "@rs_queue.consumer"
            - "@apisearch.server.event_store"
        tags:
            -  { name: console.command }