services:

    #
    # Console commands
    #
    apisearch_server.event_store_consumer:
        class: Apisearch\Server\Console\EventStoreConsumer
        arguments:
            - "@rs_queue.consumer"
            - "@apisearch_server.event_store"
            - "@rs_queue.publisher"
        tags:
            -  { name: console.command }

    apisearch_server.logs_consumer:
        class: Apisearch\Server\Console\LogsConsumer
        arguments:
            - "@rs_queue.consumer"
            - "@apisearch.log_repository_main.default"
            - "@rs_queue.publisher"
        tags:
            -  { name: console.command }


    apisearch_server.command_with_bus_and_god_token:
        class: Apisearch\Server\Console\CommandWithBusAndGodToken
        abstract: true
        arguments:
            - "@tactician.commandbus.command"
            - "%apisearch_server.god_token%"

    apisearch_server.create_index_command:
        class: Apisearch\Server\Console\CreateIndexCommand
        parent: apisearch_server.command_with_bus_and_god_token
        tags:
            -  { name: console.command }

    apisearch_server.delete_index_command:
        class: Apisearch\Server\Console\DeleteIndexCommand
        parent: apisearch_server.command_with_bus_and_god_token
        tags:
            -  { name: console.command }

    apisearch_server.check_index_command:
        class: Apisearch\Server\Console\CheckIndexCommand
        parent: apisearch_server.command_with_bus_and_god_token
        tags:
            -  { name: console.command }

    apisearch_server.add_token_command:
        class: Apisearch\Server\Console\AddTokenCommand
        parent: apisearch_server.command_with_bus_and_god_token
        tags:
            -  { name: console.command }

    apisearch_server.delete_token_command:
        class: Apisearch\Server\Console\DeleteTokenCommand
        parent: apisearch_server.command_with_bus_and_god_token
        tags:
            -  { name: console.command }