services:

    #
    # Controllers with command bus
    #
    apisearch_server.create_index_controller:
        class: Apisearch\Server\Controller\CreateIndexController
        arguments:
            - "@tactician.commandbus.command"

    apisearch_server.delete_index_controller:
        class: Apisearch\Server\Controller\DeleteIndexController
        arguments:
            - "@tactician.commandbus.command"

    apisearch_server.reset_index_controller:
        class: Apisearch\Server\Controller\ResetIndexController
        arguments:
            - "@tactician.commandbus.command"
            - "@apisearch_server.events_repository"

    apisearch_server.create_events_index_controller:
        class: Apisearch\Server\Controller\CreateEventsIndexController
        arguments:
            - "@tactician.commandbus.command"

    apisearch_server.delete_events_index_controller:
        class: Apisearch\Server\Controller\DeleteEventsIndexController
        arguments:
            - "@tactician.commandbus.command"

    apisearch_server.create_logs_index_controller:
        class: Apisearch\Server\Controller\CreateLogsIndexController
        arguments:
            - "@tactician.commandbus.command"

    apisearch_server.delete_logs_index_controller:
        class: Apisearch\Server\Controller\DeleteLogsIndexController
        arguments:
            - "@tactician.commandbus.command"

    apisearch_server.add_token_controller:
        class: Apisearch\Server\Controller\AddTokenController
        arguments:
            - "@tactician.commandbus.command"

    apisearch_server.delete_token_controller:
        class: Apisearch\Server\Controller\DeleteTokenController
        arguments:
            - "@tactician.commandbus.command"

    #
    # Controllers with query bus
    #
    apisearch_server.query_controller:
        class: Apisearch\Server\Controller\QueryController
        arguments:
            - "@tactician.commandbus.query"
            - "@apisearch_server.events_repository"

    apisearch_server.index_items_controller:
        class: Apisearch\Server\Controller\IndexItemsController
        arguments:
            - "@tactician.commandbus.command"
            - "@apisearch_server.events_repository"

    apisearch_server.delete_items_controller:
        class: Apisearch\Server\Controller\DeleteItemsController
        arguments:
            - "@tactician.commandbus.command"
            - "@apisearch_server.events_repository"

    apisearch_server.events_controller:
        class: Apisearch\Server\Controller\EventsController
        arguments:
            - "@tactician.commandbus.query"

    apisearch_server.logs_controller:
        class: Apisearch\Server\Controller\LogsController
        arguments:
            - "@tactician.commandbus.query"

    apisearch_server.configure_index_controller:
        class: Apisearch\Server\Controller\ConfigureIndexController
        arguments:
            - "@tactician.commandbus.query"
            - "@apisearch_server.events_repository"

    apisearch_server.health_controller:
        class: Apisearch\Server\Controller\HealthController
        arguments:
            - "@tactician.commandbus.query"

    apisearch_server.check_index_controller:
        class: Apisearch\Server\Controller\CheckIndexController
        arguments:
            - "@tactician.commandbus.query"

    #
    # Controller listener
    #
    apisearch_server.php_exception_to_json_response_listener:
        class: Apisearch\Server\Controller\Listener\PHPExceptionToJsonResponse
        tags:
            - { name: kernel.event_listener, event: kernel.exception }