services:

    #
    # Controllers
    #
    search_server.api_controller:
        class: Puntmig\Search\Server\Controller\ApiController
        arguments:
            - "@tactician.commandbus"
            - "@search_server.repository.query"