services:

    _defaults:
        autowire: false
        autoconfigure: false
        public: true

    #
    # Controllers with command bus
    #
    apisearch_server.create_index_controller:
        class: Apisearch\Server\Controller\CreateIndexController
        arguments:
            - "@apisearch_server.command_bus"

    apisearch_server.delete_index_controller:
        class: Apisearch\Server\Controller\DeleteIndexController
        arguments:
            - "@apisearch_server.command_bus"

    apisearch_server.reset_index_controller:
        class: Apisearch\Server\Controller\ResetIndexController
        arguments:
            - "@apisearch_server.command_bus"
            - "@apisearch_server.events_repository"

    apisearch_server.create_events_index_controller:
        class: Apisearch\Server\Controller\CreateEventsIndexController
        arguments:
            - "@apisearch_server.command_bus"

    apisearch_server.delete_events_index_controller:
        class: Apisearch\Server\Controller\DeleteEventsIndexController
        arguments:
            - "@apisearch_server.command_bus"

    apisearch_server.create_logs_index_controller:
        class: Apisearch\Server\Controller\CreateLogsIndexController
        arguments:
            - "@apisearch_server.command_bus"

    apisearch_server.delete_logs_index_controller:
        class: Apisearch\Server\Controller\DeleteLogsIndexController
        arguments:
            - "@apisearch_server.command_bus"

    apisearch_server.add_token_controller:
        class: Apisearch\Server\Controller\AddTokenController
        arguments:
            - "@apisearch_server.command_bus"

    apisearch_server.delete_token_controller:
        class: Apisearch\Server\Controller\DeleteTokenController
        arguments:
            - "@apisearch_server.command_bus"

    apisearch_server.delete_tokens_controller:
        class: Apisearch\Server\Controller\DeleteTokensController
        arguments:
            - "@apisearch_server.command_bus"

    apisearch_server.add_interaction_controller:
        class: Apisearch\Server\Controller\AddInteractionController
        arguments:
            - "@apisearch_server.command_bus"

    apisearch_server.delete_all_interactions_controller:
        class: Apisearch\Server\Controller\DeleteAllInteractionsController
        arguments:
            - "@apisearch_server.command_bus"

    apisearch_server.index_items_controller:
        class: Apisearch\Server\Controller\IndexItemsController
        arguments:
            - "@apisearch_server.command_bus"
            - "@apisearch_server.events_repository"

    apisearch_server.update_items_controller:
        class: Apisearch\Server\Controller\UpdateItemsController
        arguments:
            - "@apisearch_server.command_bus"
            - "@apisearch_server.events_repository"

    apisearch_server.delete_items_controller:
        class: Apisearch\Server\Controller\DeleteItemsController
        arguments:
            - "@apisearch_server.command_bus"
            - "@apisearch_server.events_repository"

    #
    # Controllers with query bus
    #
    apisearch_server.query_controller:
        class: Apisearch\Server\Controller\QueryController
        arguments:
            - "@apisearch_server.query_bus"
            - "@apisearch_server.events_repository"

    apisearch_server.events_controller:
        class: Apisearch\Server\Controller\EventsController
        arguments:
            - "@apisearch_server.query_bus"

    apisearch_server.logs_controller:
        class: Apisearch\Server\Controller\LogsController
        arguments:
            - "@apisearch_server.query_bus"

    apisearch_server.configure_index_controller:
        class: Apisearch\Server\Controller\ConfigureIndexController
        arguments:
            - "@apisearch_server.query_bus"
            - "@apisearch_server.events_repository"

    apisearch_server.check_health_controller:
        class: Apisearch\Server\Controller\CheckHealthController
        arguments:
            - "@apisearch_server.query_bus"

    apisearch_server.ping_controller:
        class: Apisearch\Server\Controller\PingController
        arguments:
            - "@apisearch_server.query_bus"

    apisearch_server.check_index_controller:
        class: Apisearch\Server\Controller\CheckIndexController
        arguments:
            - "@apisearch_server.query_bus"

    apisearch_server.get_tokens_controller:
        class: Apisearch\Server\Controller\GetTokensController
        arguments:
            - "@apisearch_server.query_bus"


    #
    # Controller listener
    #
    apisearch_server.php_exception_to_json_response_listener:
        class: Apisearch\Server\Controller\Listener\PHPExceptionToJsonResponse
        tags:
            - { name: kernel.event_listener, event: kernel.exception }

    apisearch_server.token_validation_over_http:
        class: Apisearch\Server\Controller\Listener\TokenValidationOverHTTP
        arguments:
            - "@apisearch_server.token_validator"
        tags:
            - { name: kernel.event_listener, event: kernel.request, method: validateTokenOnKernelRequest }

    apisearch_server.token_cache_over_http:
        class: Apisearch\Server\Controller\Listener\TokenCacheOverHTTP
        tags:
            - { name: kernel.event_listener, event: kernel.response, method: addCacheControlOnKernelResponse }