services:

    #
    # Controllers
    #
    apisearch.server.query_controller:
        class: Apisearch\Server\Controller\QueryController
        arguments:
            - "@tactician.commandbus.query"
            - "@apisearch.server.event_repository"

    apisearch.server.index_controller:
        class: Apisearch\Server\Controller\IndexController
        arguments:
            - "@tactician.commandbus.command"
            - "@apisearch.server.event_repository"

    apisearch.server.delete_controller:
        class: Apisearch\Server\Controller\DeleteController
        arguments:
            - "@tactician.commandbus.command"
            - "@apisearch.server.event_repository"

    apisearch.server.reset_controller:
        class: Apisearch\Server\Controller\ResetController
        arguments:
            - "@tactician.commandbus.command"
            - "@apisearch.server.event_repository"

    apisearch.server.events_controller:
        class: Apisearch\Server\Controller\EventsController
        arguments:
            - "@tactician.commandbus.query"
            - "@apisearch.server.event_repository"

    apisearch.server.ping_controller:
        class: Apisearch\Server\Controller\PingController

    #
    # Controller listener
    #
    apisearch.server.php_exception_to_json_response_listener:
        class: Apisearch\Server\Controller\Listener\PHPExceptionToJsonResponse
        tags:
            - { name: kernel.event_listener, event: kernel.exception }