services:

    #
    # Controllers
    #
    search_bundle.api_controller:
        class: Puntmig\Search\Server\Controller\ApiController
        arguments:
            - "@search_bundle.query_repository"
            - "@search_bundle.index_repository"