services:

    #
    # Events
    #
    apisearch_server.event_store:
        class: Apisearch\Server\Domain\Event\EventStore
        arguments:
            - "@apisearch_server.events_repository"
        tags:
            - { name: apisearch_server.domain_event_subscriber }

    apisearch_server.event_publisher:
        class: Apisearch\Server\Domain\Event\EventPublisher

    apisearch_server.inline_event_publisher:
        class: Apisearch\Server\Domain\Event\EventPublisher

    #
    # Command handlers
    #
    apisearch_server.comand_handler.configure_environment:
        class: Apisearch\Server\Domain\CommandHandler\ConfigureEnvironmentHandler
        tags:
            - { name: tactician.handler, command: Apisearch\Server\Domain\Command\ConfigureEnvironment }

    apisearch_server.comand_handler.clean_environment:
        class: Apisearch\Server\Domain\CommandHandler\CleanEnvironmentHandler
        tags:
            - { name: tactician.handler, command: Apisearch\Server\Domain\Command\CleanEnvironment }

    apisearch_server.comand_handler.create_index:
        class: Apisearch\Server\Domain\CommandHandler\CreateIndexHandler
        arguments:
            - "@apisearch.repository_main.default"
            - "@apisearch_server.inline_event_publisher"
        tags:
            - { name: tactician.handler, command: Apisearch\Server\Domain\Command\CreateIndex }

    apisearch_server.comand_handler.delete_index:
        class: Apisearch\Server\Domain\CommandHandler\DeleteIndexHandler
        arguments:
            - "@apisearch.repository_main.default"
            - "@apisearch_server.inline_event_publisher"
        tags:
            - { name: tactician.handler, command: Apisearch\Server\Domain\Command\DeleteIndex }

    apisearch_server.comand_handler.reset_index:
        class: Apisearch\Server\Domain\CommandHandler\ResetIndexHandler
        arguments:
            - "@apisearch.repository_main.default"
            - "@apisearch_server.inline_event_publisher"
        tags:
            - { name: tactician.handler, command: Apisearch\Server\Domain\Command\ResetIndex }

    apisearch_server.comand_handler.configure_index:
        class: Apisearch\Server\Domain\CommandHandler\ConfigureIndexHandler
        arguments:
            - "@apisearch.repository_main.default"
            - "@apisearch_server.inline_event_publisher"
        tags:
            - { name: tactician.handler, command: Apisearch\Server\Domain\Command\ConfigureIndex }

    apisearch_server.comand_handler.delete_items:
        class: Apisearch\Server\Domain\CommandHandler\DeleteItemsHandler
        arguments:
            - "@apisearch.repository_main.default"
            - "@apisearch_server.inline_event_publisher"
        tags:
            - { name: tactician.handler, command: Apisearch\Server\Domain\Command\DeleteItems }

    apisearch_server.comand_handler.index_items:
        class: Apisearch\Server\Domain\CommandHandler\IndexItemsHandler
        arguments:
            - "@apisearch.repository_main.default"
            - "@apisearch_server.inline_event_publisher"
        tags:
            - { name: tactician.handler, command: Apisearch\Server\Domain\Command\IndexItems }

    apisearch_server.comand_handler.update_items:
        class: Apisearch\Server\Domain\CommandHandler\UpdateItemsHandler
        arguments:
            - "@apisearch.repository_main.default"
            - "@apisearch_server.inline_event_publisher"
        tags:
            - { name: tactician.handler, command: Apisearch\Server\Domain\Command\UpdateItems }

    apisearch_server.comand_handler.add_token:
        class: Apisearch\Server\Domain\CommandHandler\AddTokenHandler
        arguments:
            - "@apisearch.app_repository_main"
            - "@apisearch_server.inline_event_publisher"
        tags:
            - { name: tactician.handler, command: Apisearch\Server\Domain\Command\AddToken }

    apisearch_server.comand_handler.delete_token:
        class: Apisearch\Server\Domain\CommandHandler\DeleteTokenHandler
        arguments:
            - "@apisearch.app_repository_main"
            - "@apisearch_server.inline_event_publisher"
        tags:
            - { name: tactician.handler, command: Apisearch\Server\Domain\Command\DeleteToken }

    apisearch_server.comand_handler.delete_tokens:
        class: Apisearch\Server\Domain\CommandHandler\DeleteTokensHandler
        arguments:
            - "@apisearch.app_repository_main"
            - "@apisearch_server.inline_event_publisher"
        tags:
            - { name: tactician.handler, command: Apisearch\Server\Domain\Command\DeleteTokens }

    apisearch_server.comand_handler.add_interaction:
        class: Apisearch\Server\Domain\CommandHandler\AddInteractionHandler
        arguments:
            - "@apisearch.user_repository_main"
            - "@apisearch_server.inline_event_publisher"
        tags:
            - { name: tactician.handler, command: Apisearch\Server\Domain\Command\AddInteraction }

    apisearch_server.comand_handler.delete_all_interaction:
        class: Apisearch\Server\Domain\CommandHandler\DeleteAllInteractionsHandler
        arguments:
            - "@apisearch.user_repository_main"
            - "@apisearch_server.inline_event_publisher"
        tags:
            - { name: tactician.handler, command: Apisearch\Server\Domain\Command\DeleteAllInteractions }

    #
    # Query handlers
    #
    apisearch_server.query_handler.query:
        class: Apisearch\Server\Domain\QueryHandler\QueryHandler
        arguments:
            - "@apisearch.repository_main.default"
            - "@apisearch_server.inline_event_publisher"
        tags:
            - { name: tactician.handler, command: Apisearch\Server\Domain\Query\Query }

    apisearch_server.query_handler.check_index:
        class: Apisearch\Server\Domain\QueryHandler\CheckIndexHandler
        arguments:
            - "@apisearch.repository_main.default"
        tags:
            - { name: tactician.handler, command: Apisearch\Server\Domain\Query\CheckIndex }

    apisearch_server.query_handler.query_events:
        class: Apisearch\Server\Domain\QueryHandler\QueryEventsHandler
        arguments:
            - "@apisearch.event_repository_main.default"
        tags:
            - { name: tactician.handler, command: Apisearch\Server\Domain\Query\QueryEvents }

    apisearch_server.query_handler.query_logs:
        class: Apisearch\Server\Domain\QueryHandler\QueryLogsHandler
        arguments:
            - "@apisearch.log_repository_main.default"
        tags:
            - { name: tactician.handler, command: Apisearch\Server\Domain\Query\QueryLogs }

    apisearch_server.query_handler.get_tokens:
        class: Apisearch\Server\Domain\QueryHandler\GetTokensHandler
        arguments:
            - "@apisearch.app_repository_main"
            - "@apisearch_server.inline_event_publisher"
        tags:
            - { name: tactician.handler, command: Apisearch\Server\Domain\Query\GetTokens }

    apisearch_server.query_handler.check_health:
        class: Apisearch\Server\Domain\QueryHandler\CheckHealthHandler
        tags:
            - { name: tactician.handler, command: Apisearch\Server\Domain\Query\CheckHealth }

    apisearch_server.query_handler.ping:
        class: Apisearch\Server\Domain\QueryHandler\PingHandler
        tags:
            - { name: tactician.handler, command: Apisearch\Server\Domain\Query\Ping }

    #
    # Command bus
    #
    apisearch_server.query_bus:
        alias: "tactician.commandbus.query"

    apisearch_server.command_bus.inline:
        class: Apisearch\Server\Domain\CommandBus\InlineCommandBus
        arguments:
            - "@tactician.commandbus.command"

    apisearch_server.command_bus.asynchronous:
        class: Apisearch\Server\Domain\CommandBus\AsynchronousCommandBus
        arguments:
            - "@rs_queue.producer"
            - "@tactician.commandbus.command"

    #
    # Middlewares Domain Events
    #
    apisearch_server.middleware.ignore_events:
        class: Apisearch\Server\Domain\Middleware\DomainEvents\IgnoreDomainEventsMiddleware
        arguments:
            - "@apisearch_server.inline_event_publisher"
        public: false

    apisearch_server.middleware.inline_events:
        class: Apisearch\Server\Domain\Middleware\DomainEvents\InlineDomainEventsMiddleware
        arguments:
            - "@apisearch_server.inline_event_publisher"
            - "@apisearch_server.event_publisher"
        public: false

    apisearch_server.middleware.queue_events:
        class: Apisearch\Server\Domain\Middleware\DomainEvents\QueueDomainEventsMiddleware
        arguments:
            - "@apisearch_server.inline_event_publisher"
            - "@rs_queue.producer"
        public: false

    #
    # Middlewares Logs
    #
    apisearch_server.middleware.ignore_logs:
        class: Apisearch\Server\Domain\Middleware\Logs\IgnoreLogsMiddleware
        public: false

    apisearch_server.middleware.inline_logs:
        class: Apisearch\Server\Domain\Middleware\Logs\InlineLogsMiddleware
        arguments:
            - "@apisearch.log_repository_main.default"
        public: false

    apisearch_server.middleware.queue_logs:
        class: Apisearch\Server\Domain\Middleware\Logs\QueueLogsMiddleware
        arguments:
            - "@rs_queue.producer"
        public: false

    #
    # Domain Middlewares
    #
    apisearch_server.middleware.interactions:
        class: Apisearch\Server\Domain\Middleware\InteractionsMiddleware
        arguments:
            - "@apisearch.user_repository_main"
        public: false

    apisearch_server.middleware.repository_reference:
        class: Apisearch\Server\Domain\Middleware\RepositoryReferenceMiddleware
        public: false

    apisearch_server.middleware.token:
        class: Apisearch\Server\Domain\Middleware\TokenMiddleware
        public: false

    apisearch_server.middleware.plugins:
        class: Apisearch\Server\Domain\Plugin\PluginMiddlewareCollector
        arguments:
            - "%apisearch_server.enabled_plugins%"

    #
    # Repositories
    #
    apisearch_server.items_repository:
        class: Apisearch\Server\Domain\Repository\Repository\Repository

    apisearch_server.events_repository:
        class: Apisearch\Server\Domain\Repository\EventRepository\Repository

    apisearch_server.logs_repository:
        class: Apisearch\Server\Domain\Repository\LogRepository\Repository

    apisearch_server.app_repository:
        class: Apisearch\Server\Domain\Repository\AppRepository\Repository

    apisearch_server.user_repository:
        class: Apisearch\Server\Domain\Repository\UserRepository\Repository

    #
    # Token
    #
    apisearch_server.static_token_locator:
        class: Apisearch\Server\Domain\Token\StaticTokenLocator
        arguments:
            - "%apisearch_server.god_token%"
            - "%apisearch_server.readonly_token%"
            - "%apisearch_server.ping_token%"
        tags:
            - { name: apisearch_server.token_locator }

    apisearch_server.token_validator:
        class: Apisearch\Server\Domain\Token\TokenValidator