services:

    #
    # Events
    #
    apisearch.server.event_repository:
        alias: "apisearch.server.elastica_event_repository"

    apisearch.server.event_store:
        class: Apisearch\Server\Domain\Event\EventStore
        arguments:
            - "@apisearch.server.event_repository"

    apisearch.server.event_publisher:
        class: Apisearch\Server\Domain\Event\EventPublisher


    #
    # Command handlers
    #
    apisearch.server.comand_handler.delete:
        class: Apisearch\Server\Domain\CommandHandler\DeleteHandler
        arguments:
            - "@apisearch.repository_search.default"
            - "@apisearch.server.event_publisher"
        tags:
            - { name: tactician.handler, command: Apisearch\Server\Domain\Command\Delete }

    apisearch.server.comand_handler.index:
        class: Apisearch\Server\Domain\CommandHandler\IndexHandler
        arguments:
            - "@apisearch.repository_search.default"
            - "@apisearch.server.event_publisher"
        tags:
            - { name: tactician.handler, command: Apisearch\Server\Domain\Command\Index }

    apisearch.server.comand_handler.reset:
        class: Apisearch\Server\Domain\CommandHandler\ResetHandler
        arguments:
            - "@apisearch.repository_search.default"
            - "@apisearch.server.event_publisher"
            - "@apisearch.server.event_repository"
        tags:
            - { name: tactician.handler, command: Apisearch\Server\Domain\Command\Reset }

    #
    # Query handlers
    #
    apisearch.server.query_handler.query:
        class: Apisearch\Server\Domain\QueryHandler\QueryHandler
        arguments:
            - "@apisearch.repository_search.default"
            - "@apisearch.server.event_publisher"
        tags:
            - { name: tactician.handler, command: Apisearch\Server\Domain\Query\Query }

    apisearch.server.query_handler.list_events:
        class: Apisearch\Server\Domain\QueryHandler\ListEventsHandler
        arguments:
            - "@apisearch.event_repository_search.default"
        tags:
            - { name: tactician.handler, command: Apisearch\Server\Domain\Query\ListEvents }

    apisearch.server.query_handler.stats_events:
        class: Apisearch\Server\Domain\QueryHandler\StatsEventsHandler
        arguments:
            - "@apisearch.event_repository_search.default"
        tags:
            - { name: tactician.handler, command: Apisearch\Server\Domain\Query\StatsEvents }

    #
    # Middlewares
    #
    apisearch.server.middleware.ignore_domain_events:
        class: Apisearch\Server\Domain\Middleware\IgnoreDomainEventsMiddleware
        arguments:
            - "@apisearch.server.event_publisher"
        public: false

    apisearch.server.middleware.inline_events:
        class: Apisearch\Server\Domain\Middleware\InlineDomainEventsMiddleware
        arguments:
            - "@apisearch.server.event_publisher"
            - "@apisearch.server.event_store"
        public: false

    apisearch.server.middleware.queue_events:
        class: Apisearch\Server\Domain\Middleware\QueueDomainEventsMiddleware
        arguments:
            - "@apisearch.server.event_publisher"
            - "@rs_queue.producer"
        public: false

    apisearch.server.middleware.domain_events:
        alias: "apisearch.server.middleware.queue_events"