services:

    #
    # Events
    #
    search_server.event_repository:
        alias: "search_server.elastica_event_repository"

    search_server.event_store:
        class: Puntmig\Search\Server\Domain\Event\EventStore
        arguments:
            - "@search_server.event_repository"

    search_server.event_publisher:
        class: Puntmig\Search\Server\Domain\Event\EventPublisher


    #
    # Command handlers
    #
    search_server.comand_handler.delete:
        class: Puntmig\Search\Server\Domain\CommandHandler\DeleteHandler
        arguments:
            - "@puntmig_search.repository_search"
            - "@search_server.event_publisher"
        tags:
            - { name: tactician.handler, command: Puntmig\Search\Server\Domain\Command\Delete }

    search_server.comand_handler.index:
        class: Puntmig\Search\Server\Domain\CommandHandler\IndexHandler
        arguments:
            - "@puntmig_search.repository_search"
            - "@search_server.event_publisher"
        tags:
            - { name: tactician.handler, command: Puntmig\Search\Server\Domain\Command\Index }

    search_server.comand_handler.reset:
        class: Puntmig\Search\Server\Domain\CommandHandler\ResetHandler
        arguments:
            - "@puntmig_search.repository_search"
            - "@search_server.event_publisher"
            - "@search_server.event_repository"
        tags:
            - { name: tactician.handler, command: Puntmig\Search\Server\Domain\Command\Reset }

    #
    # Query handlers
    #
    search_server.query_handler.query:
        class: Puntmig\Search\Server\Domain\QueryHandler\QueryHandler
        arguments:
            - "@puntmig_search.repository_search"
            - "@search_server.event_publisher"
        tags:
            - { name: tactician.handler, command: Puntmig\Search\Server\Domain\Query\Query }

    search_server.query_handler.list_events:
        class: Puntmig\Search\Server\Domain\QueryHandler\ListEventsHandler
        arguments:
            - "@puntmig_search.event_repository_search"
        tags:
            - { name: tactician.handler, command: Puntmig\Search\Server\Domain\Query\ListEvents }

    search_server.query_handler.stats_events:
        class: Puntmig\Search\Server\Domain\QueryHandler\StatsEventsHandler
        arguments:
            - "@puntmig_search.event_repository_search"
        tags:
            - { name: tactician.handler, command: Puntmig\Search\Server\Domain\Query\StatsEvents }

    #
    # Middlewares
    #
    search_server.middleware.domain_events:
        class: Puntmig\Search\Server\Domain\Middleware\DomainEventsMiddleware
        arguments:
            - "@search_server.event_store"
            - "@search_server.event_publisher"
        public: false
