services:

    #
    # Elastica related services
    #
    search_server.elastica_client:
        class: Elastica\Client
        arguments:
            - { servers: { default: { host: localhost, port: 9200}}}

    search_server.elastica_wrapper:
        class: Puntmig\Search\Server\Elastica\ElasticaWrapper
        arguments:
            - "@search_server.elastica_client"

    #
    # Elastica repositories
    #
    search_server.elastica_with_key_wrapper:
        class: Puntmig\Search\Server\Elastica\ElasticaWithKeyWrapper
        abstract: true
        public: false
        arguments:
            - "@search_server.elastica_wrapper"

    search_server.elastica_query_repository:
        class: Puntmig\Search\Server\Elastica\Repository\QueryRepository
        parent: search_server.elastica_with_key_wrapper

    search_server.elastica_index_repository:
        class: Puntmig\Search\Server\Elastica\Repository\IndexRepository
        parent: search_server.elastica_with_key_wrapper

    search_server.elastica_delete_repository:
        class: Puntmig\Search\Server\Elastica\Repository\DeleteRepository
        parent: search_server.elastica_with_key_wrapper

    #
    # Adapters
    #
    search_server.elastica_repository:
        class: Puntmig\Search\Server\Elastica\Repository\Repository
        arguments:
            - "@search_server.elastica_query_repository"
            - "@search_server.elastica_index_repository"
            - "@search_server.elastica_delete_repository"

    #
    # Middlewares
    #
    search_server.middleware.log_all_domain_events_to_elastica:
        class: Puntmig\Search\Server\Elastica\Middleware\LogAllDomainEventsToElasticaMiddleware
        arguments:
            - "@search_server.elastica_client"
            - "@search_server.event_publisher"
        public: false

    search_server.middleware.transaction:
        class: Puntmig\Search\Server\Elastica\Middleware\TransactionElasticaMiddleware
        arguments:
            - "@puntmig_search.repository_search"