services:

    #
    # Elastica related services
    #
    apisearch_server.elastica_client:
        class: Elastica\Client
        arguments:
            - "%apisearch_server.cluster%"

    apisearch_server.query_builder:
        class: Apisearch\Server\Elastica\Builder\QueryBuilder

    apisearch_server.result_builder:
        class: Apisearch\Server\Elastica\Builder\ResultBuilder

    apisearch_server.time_format_builder:
        class: Apisearch\Server\Elastica\Builder\TimeFormatBuilder

    #
    # Elastica repositories
    #
    apisearch_server.item_elastica_wrapper:
        class: Apisearch\Server\Elastica\Repository\ItemElasticaWrapper
        arguments:
            - "@apisearch_server.elastica_client"

    apisearch_server.item_elastica_with_app_id_wrapper:
        class: Apisearch\Server\Elastica\ElasticaWithAppIdWrapper
        abstract: true
        public: false
        arguments:
            - "@apisearch_server.item_elastica_wrapper"
            - "%apisearch_server.config.repository%"

    apisearch_server.elastica_query_repository:
        class: Apisearch\Server\Elastica\Repository\QueryRepository
        parent: apisearch_server.item_elastica_with_app_id_wrapper
        arguments:
            - "@apisearch_server.query_builder"
            - "@apisearch_server.result_builder"
        tags:
            - {name: "apisearch_server.items_repository"}

    apisearch_server.elastica_index_repository:
        class: Apisearch\Server\Elastica\Repository\IndexRepository
        parent: apisearch_server.item_elastica_with_app_id_wrapper
        tags:
            - {name: "apisearch_server.items_repository"}

    apisearch_server.elastica_delete_repository:
        class: Apisearch\Server\Elastica\Repository\DeleteRepository
        parent: apisearch_server.item_elastica_with_app_id_wrapper
        tags:
            - {name: "apisearch_server.items_repository"}

    apisearch_server.elastica_config_repository:
        class: Apisearch\Server\Elastica\Repository\ConfigRepository
        parent: apisearch_server.item_elastica_with_app_id_wrapper
        tags:
            - {name: "apisearch_server.items_repository"}


    #
    # Elastica event repositories
    #
    apisearch_server.event_elastica_wrapper:
        class: Apisearch\Server\Elastica\EventRepository\EventElasticaWrapper
        arguments:
            - "@apisearch_server.elastica_client"

    apisearch_server.event_elastica_with_app_id_wrapper:
        class: Apisearch\Server\Elastica\ElasticaWithAppIdWrapper
        abstract: true
        public: false
        arguments:
            - "@apisearch_server.event_elastica_wrapper"
            - "%apisearch_server.config.event_repository%"

    apisearch_server.elastica_query_event_repository:
        class: Apisearch\Server\Elastica\EventRepository\QueryRepository
        parent: apisearch_server.event_elastica_with_app_id_wrapper
        arguments:
            - "@apisearch_server.query_builder"
            - "@apisearch_server.result_builder"
        tags:
            - {name: "apisearch_server.events_repository"}

    apisearch_server.elastica_index_event_repository:
        class: Apisearch\Server\Elastica\EventRepository\IndexRepository
        parent: apisearch_server.event_elastica_with_app_id_wrapper
        arguments:
            - "@apisearch_server.time_format_builder"
        tags:
            - {name: "apisearch_server.events_repository"}


    #
    # Elastica log repositories
    #
    apisearch_server.log_elastica_wrapper:
        class: Apisearch\Server\Elastica\LogRepository\LogElasticaWrapper
        arguments:
            - "@apisearch_server.elastica_client"

    apisearch_server.log_elastica_with_app_id_wrapper:
        class: Apisearch\Server\Elastica\ElasticaWithAppIdWrapper
        abstract: true
        public: false
        arguments:
            - "@apisearch_server.log_elastica_wrapper"
            - "%apisearch_server.config.log_repository%"

    apisearch_server.elastica_query_log_repository:
        class: Apisearch\Server\Elastica\LogRepository\QueryRepository
        parent: apisearch_server.log_elastica_with_app_id_wrapper
        arguments:
            - "@apisearch_server.query_builder"
            - "@apisearch_server.result_builder"
        tags:
            - {name: "apisearch_server.logs_repository"}

    apisearch_server.elastica_index_log_repository:
        class: Apisearch\Server\Elastica\LogRepository\IndexRepository
        parent: apisearch_server.log_elastica_with_app_id_wrapper
        arguments:
            - "@apisearch_server.time_format_builder"
        tags:
            - {name: "apisearch_server.logs_repository"}


    #
    # Middlewares
    #
    apisearch_server.middleware.log_all_domain_events_to_elastica:
        class: Apisearch\Server\Elastica\Middleware\LogAllDomainEventsToElasticaMiddleware
        arguments:
            - "@apisearch_server.elastica_client"
            - "@apisearch_server.event_publisher"
        public: false

    apisearch_server.middleware.transaction:
        class: Apisearch\Server\Elastica\Middleware\TransactionElasticaMiddleware
        arguments:
            - "@apisearch.repository_main.default"