services:

    #
    # Http clients
    #
    search_bundle.guzzle_client:
        class: Mmoreram\SearchBundle\Http\GuzzleClient
        arguments:
            - "localhost:8000"

    search_bundle.http_client:
        alias: search_bundle.guzzle_client