services:

    #
    # Core repositories
    #
    search_bundle.query_repository:
        class: Puntmig\Search\Server\Core\QueryRepository
        arguments:
            - "@search_bundle.elastica_wrapper"

    search_bundle.index_repository:
        class: Puntmig\Search\Server\Core\IndexRepository
        arguments:
            - "@search_bundle.elastica_wrapper"

    #
    # Adapters
    #
    search_bundle.service_repository:
        class: Puntmig\Search\Server\Repository\ServiceRepository
        arguments:
            - "@search_bundle.query_repository"
            - "@search_bundle.index_repository"
