services:

    #
    # Core repositories
    #
    search_bundle.elastica_with_key_wrapper:
        class: Puntmig\Search\Server\Core\ElasticaWithKeyWrapper
        abstract: true
        public: false
        arguments:
            - "@search_bundle.elastica_wrapper"

    search_bundle.query_repository:
        class: Puntmig\Search\Server\Core\QueryRepository
        parent: search_bundle.elastica_with_key_wrapper

    search_bundle.index_repository:
        class: Puntmig\Search\Server\Core\IndexRepository
        parent: search_bundle.elastica_with_key_wrapper

    search_bundle.delete_repository:
        class: Puntmig\Search\Server\Core\DeleteRepository
        parent: search_bundle.elastica_with_key_wrapper

    #
    # Adapters
    #
    search_bundle.service_repository:
        class: Puntmig\Search\Server\Repository\ServiceRepository
        arguments:
            - "@search_bundle.query_repository"
            - "@search_bundle.index_repository"
            - "@search_bundle.delete_repository"
