services:

    search_bundle.repository:
        class: Mmoreram\SearchBundle\Repository\Repository
        arguments:
            - "@search_bundle.elastica_wrapper"

    search_bundle.index:
        class: Mmoreram\SearchBundle\Repository\Index
        arguments:
            - "@search_bundle.elastica_wrapper"