#
# Token API
#
apisearch_v1_put_token:
    path: /v1/{app_id}/tokens
    methods: ["PUT"]
    defaults:
        _controller: apisearch_server.add_token_controller

apisearch_v1_delete_token:
    path: /v1/{app_id}/tokens/{token_id}
    methods: ["DELETE"]
    defaults:
        _controller: apisearch_server.delete_token_controller

apisearch_v1_get_tokens:
    path: /v1/{app_id}/tokens
    methods: ["GET"]
    defaults:
        _controller: apisearch_server.get_tokens_controller

apisearch_v1_delete_tokens:
    path: /v1/{app_id}/tokens
    methods: ["DELETE"]
    defaults:
        _controller: apisearch_server.delete_tokens_controller

#
# Index API
#
apisearch_v1_get_indices:
    path: /v1/{app_id}/indices
    methods: ["GET"]
    defaults:
        _controller: apisearch_server.get_indices_controller

apisearch_v1_put_index:
    path: /v1/{app_id}/indices/{index_id}
    methods: ["PUT"]
    defaults:
        _controller: apisearch_server.create_index_controller

apisearch_v1_delete_index:
    path: /v1/{app_id}/indices/{index_id}
    methods: ["DELETE"]
    defaults:
        _controller: apisearch_server.delete_index_controller

apisearch_v1_reset_index:
    path: /v1/{app_id}/indices/{index_id}/reset
    methods: ["POST"]
    defaults:
        _controller: apisearch_server.reset_index_controller

apisearch_v1_configure_index:
    path: /v1/{app_id}/indices/{index_id}/configure
    methods: ["POST"]
    defaults:
        _controller: apisearch_server.configure_index_controller

apisearch_v1_check_index:
    path: /v1/{app_id}/indices/{index_id}
    methods: ["HEAD"]
    defaults:
        _controller: apisearch_server.check_index_controller

#
# Items API
#
apisearch_v1_put_items:
    path: /v1/{app_id}/indices/{index_id}/items
    methods: ["PUT"]
    defaults:
        _controller: apisearch_server.index_items_controller

apisearch_v1_update_items_by_query:
    path: /v1/{app_id}/indices/{index_id}/items/update-by-query
    methods: ["POST"]
    defaults:
        _controller: apisearch_server.update_items_by_query_controller

apisearch_v1_delete_items:
    path: /v1/{app_id}/indices/{index_id}/items
    methods: ["DELETE"]
    defaults:
        _controller: apisearch_server.delete_items_controller

#
# Query API
#
apisearch_v1_query:
    path: /v1/{app_id}/indices/{index_id}
    methods: ["GET"]
    defaults:
        _controller: apisearch_server.query_controller

apisearch_v1_query_all_indices:
    path: /v1/{app_id}
    methods: ["GET"]
    defaults:
        _controller: apisearch_server.query_controller
        index_id: "*"

apisearch_v1_query_short:
    path: /v1
    methods: ["GET"]
    defaults:
        _controller: apisearch_server.query_controller

#
# Interaction API
#
apisearch_v1_post_interaction:
    path: /v1/{app_id}/interactions
    methods: ["POST"]
    defaults:
        _controller: apisearch_server.add_interaction_controller

#
# Server API
#
apisearch_check_health:
    path: /health
    methods: ["GET"]
    defaults:
        _controller: apisearch_server.check_health_controller

apisearch_ping:
    path: /
    methods: ["HEAD"]
    defaults:
        _controller: apisearch_server.ping_controller

#
# Consumers management
#
apisearch_pause_consumers:
    path: /consumers/pause
    methods: ["POST"]
    defaults:
        _controller: apisearch_server.pause_consumers_controller

apisearch_resume_consumers:
    path: /consumers/resume
    methods: ["POST"]
    defaults:
        _controller: apisearch_server.resume_consumers_controller
