search_server_api_create_index:
    path: /v1/index
    methods: ["POST"]
    defaults:
        _controller: apisearch_server.create_index_controller

search_server_api_delete_index:
    path: /v1/index
    methods: ["DELETE"]
    defaults:
        _controller: apisearch_server.delete_index_controller

search_server_api_reset_index:
    path: /v1/index/reset
    methods: ["POST"]
    defaults:
        _controller: apisearch_server.reset_index_controller

search_server_api_configure_index:
    path: /v1/index/config
    methods: ["POST"]
    defaults:
        _controller: apisearch_server.configure_index_controller

search_server_api_create_events_index:
    path: /v1/events
    methods: ["POST"]
    defaults:
        _controller: apisearch_server.create_events_index_controller

search_server_api_delete_events_index:
    path: /v1/events
    methods: ["DELETE"]
    defaults:
        _controller: apisearch_server.delete_events_index_controller

search_server_api_create_logs_index:
    path: /v1/logs
    methods: ["POST"]
    defaults:
        _controller: apisearch_server.create_logs_index_controller

search_server_api_delete_logs_index:
    path: /v1/logs
    methods: ["DELETE"]
    defaults:
        _controller: apisearch_server.delete_logs_index_controller

search_server_api_add_token:
    path: /v1/token
    methods: ["POST"]
    defaults:
        _controller: apisearch_server.add_token_controller

search_server_api_delete_token:
    path: /v1/token
    methods: ["DELETE"]
    defaults:
        _controller: apisearch_server.delete_token_controller

search_server_api_get_tokens:
    path: /v1/token
    methods: ["GET"]
    defaults:
        _controller: apisearch_server.get_tokens_controller

search_server_api_add_interaction:
    path: /v1/interaction
    methods: ["GET"]
    defaults:
        _controller: apisearch_server.add_interaction_controller

search_server_api_delete_all_interaction:
    path: /v1/interactions
    methods: ["DELETE"]
    defaults:
        _controller: apisearch_server.delete_all_interactions_controller

search_server_api_query:
    path: /v1
    methods: ["GET"]
    defaults:
        _controller: apisearch_server.query_controller

search_server_api_index:
    path: /v1/items
    methods: ["POST"]
    defaults:
        _controller: apisearch_server.index_items_controller

search_server_api_update:
    path: /v1/items
    methods: ["PUT"]
    defaults:
        _controller: apisearch_server.update_items_controller

search_server_api_delete:
    path: /v1/items
    methods: ["DELETE"]
    defaults:
        _controller: apisearch_server.delete_items_controller

search_server_api_events:
    path: /v1/events
    methods: ["GET"]
    defaults:
        _controller: apisearch_server.events_controller

search_server_api_logs:
    path: /v1/logs
    methods: ["GET"]
    defaults:
        _controller: apisearch_server.logs_controller

#
# Check
#
search_server_api_check_index:
    path: /v1/index
    methods: ["HEAD"]
    defaults:
        _controller: apisearch_server.check_index_controller

search_server_api_check_health:
    path: /health
    methods: ["GET"]
    defaults:
        _controller: apisearch_server.check_health_controller

search_server_api_ping:
    path: /
    methods: ["HEAD"]
    defaults:
        _controller: apisearch_server.ping_controller