#
# Write endpoints
#
search_server_api_create_index:
    path: /v1/index
    methods: ["POST"]
    defaults:
        _controller: apisearch_server.create_index_controller:createIndex

search_server_api_delete_index:
    path: /v1/index
    methods: ["DELETE"]
    defaults:
        _controller: apisearch_server.delete_index_controller:deleteIndex

search_server_api_reset_index:
    path: /v1/index/reset
    methods: ["POST"]
    defaults:
        _controller: apisearch_server.reset_index_controller:resetIndex

search_server_api_configure_index:
    path: /v1/index/config
    methods: ["POST"]
    defaults:
        _controller: apisearch_server.configure_index_controller:configureIndex

search_server_api_create_events_index:
    path: /v1/events
    methods: ["POST"]
    defaults:
        _controller: apisearch_server.create_events_index_controller:createEventsIndex

search_server_api_delete_events_index:
    path: /v1/events
    methods: ["DELETE"]
    defaults:
        _controller: apisearch_server.delete_events_index_controller:deleteEventsIndex

search_server_api_create_logs_index:
    path: /v1/logs
    methods: ["POST"]
    defaults:
        _controller: apisearch_server.create_logs_index_controller:createLogsIndex

search_server_api_delete_logs_index:
    path: /v1/logs
    methods: ["DELETE"]
    defaults:
        _controller: apisearch_server.delete_logs_index_controller:deleteLogsIndex

search_server_api_add_token:
    path: /v1/token
    methods: ["POST"]
    defaults:
        _controller: apisearch_server.add_token_controller:addToken

search_server_api_delete_token:
    path: /v1/token
    methods: ["DELETE"]
    defaults:
        _controller: apisearch_server.delete_token_controller:deleteToken

#
# Read endpoints
#
search_server_api_query:
    path: /v1
    methods: ["GET"]
    defaults:
        _controller: apisearch_server.query_controller:query

search_server_api_index:
    path: /v1/items
    methods: ["POST"]
    defaults:
        _controller: apisearch_server.index_items_controller:indexItems

search_server_api_delete:
    path: /v1/items
    methods: ["DELETE"]
    defaults:
        _controller: apisearch_server.delete_items_controller:deleteItems

search_server_api_events:
    path: /v1/events
    methods: ["GET"]
    defaults:
        _controller: apisearch_server.events_controller:query

search_server_api_logs:
    path: /v1/logs
    methods: ["GET"]
    defaults:
        _controller: apisearch_server.logs_controller:query

#
# Check
#
search_server_api_check_index:
    path: /v1/index
    methods: ["HEAD"]
    defaults:
        _controller: apisearch_server.check_index_controller:checkIndex

search_server_api_health:
    path: /health
    methods: ["GET"]
    defaults:
        _controller: apisearch_server.health_controller:check

search_server_api_ping:
    path: /ping
    methods: ["HEAD", "GET"]
    defaults:
        _controller: apisearch_server.health_controller:ping