#
# API
#
api_query:
    path: /query
    defaults:
        _controller: search_bundle.api_controller:query

api_reset:
    path: /reset
    methods: ["DELETE"]
    defaults:
        _controller: search_bundle.api_controller:reset

api_index_products:
    path: /index/products
    methods: ["POST"]
    defaults:
        _controller: search_bundle.api_controller:index
        parameterName: products
        objectNamespace: Puntmig\Search\Model\Product
        method: addProducts

api_index_categories:
    path: /index/categories
    methods: ["POST"]
    defaults:
        _controller: search_bundle.api_controller:index
        parameterName: categories
        objectNamespace: Puntmig\Search\Model\Category
        method: addCategories

api_index_manufacturers:
    path: /index/manufacturers
    methods: ["POST"]
    defaults:
        _controller: search_bundle.api_controller:index
        parameterName: manufacturers
        objectNamespace: Puntmig\Search\Model\Manufacturer
        method: addManufacturers

api_index_brands:
    path: /index/brands
    methods: ["POST"]
    defaults:
        _controller: search_bundle.api_controller:index
        parameterName: brands
        objectNamespace: Puntmig\Search\Model\Brand
        method: addBrands

api_index_tags:
    path: /index/tags
    methods: ["POST"]
    defaults:
        _controller: search_bundle.api_controller:index
        parameterName: tags
        objectNamespace: Puntmig\Search\Model\Tag
        method: addTags
