#
# API
#
search_server_api_query:
    path: /
    methods: ["GET"]
    defaults:
        _controller: search_server.api_controller:query

search_server_api_reset:
    path: /
    methods: ["DELETE"]
    defaults:
        _controller: search_server.api_controller:reset

search_server_api_index:
    path: /items
    methods: ["POST"]
    defaults:
        _controller: search_server.api_controller:index

search_server_api_delete:
    path: /items
    methods: ["DELETE"]
    defaults:
        _controller: search_server.api_controller:delete
