#
# API
#
api_query:
    path: /query
    defaults:
        _controller: search_bundle.api_controller:query

api_reset:
    path: /reset
    methods: ["DELETE"]
    defaults:
        _controller: search_bundle.api_controller:reset

api_index_products:
    path: /products
    methods: ["POST"]
    defaults:
        _controller: search_bundle.api_controller:index
        parameterName: products
        objectNamespace: Puntmig\Search\Model\Product
        method: addProducts

api_index_categories:
    path: /categories
    methods: ["POST"]
    defaults:
        _controller: search_bundle.api_controller:index
        parameterName: categories
        objectNamespace: Puntmig\Search\Model\Category
        method: addCategories

api_index_manufacturers:
    path: /manufacturers
    methods: ["POST"]
    defaults:
        _controller: search_bundle.api_controller:index
        parameterName: manufacturers
        objectNamespace: Puntmig\Search\Model\Manufacturer
        method: addManufacturers

api_index_brands:
    path: /brands
    methods: ["POST"]
    defaults:
        _controller: search_bundle.api_controller:index
        parameterName: brands
        objectNamespace: Puntmig\Search\Model\Brand
        method: addBrands

api_index_tags:
    path: /tags
    methods: ["POST"]
    defaults:
        _controller: search_bundle.api_controller:index
        parameterName: tags
        objectNamespace: Puntmig\Search\Model\Tag
        method: addTags

api_delete_products:
    path: /products
    methods: ["DELETE"]
    defaults:
        _controller: search_bundle.api_controller:delete
        parameterName: products
        method: deleteProducts

api_delete_categories:
    path: /categories
    methods: ["DELETE"]
    defaults:
        _controller: search_bundle.api_controller:delete
        parameterName: categories
        method: deleteCategories

api_delete_manufacturers:
    path: /manufacturers
    methods: ["DELETE"]
    defaults:
        _controller: search_bundle.api_controller:delete
        parameterName: manufacturers
        method: deleteManufacturers

api_delete_brands:
    path: /brands
    methods: ["DELETE"]
    defaults:
        _controller: search_bundle.api_controller:delete
        parameterName: brands
        method: deleteBrands

api_delete_tags:
    path: /tags
    methods: ["DELETE"]
    defaults:
        _controller: search_bundle.api_controller:delete
        parameterName: tags
        method: deleteTags