tactician:
    default_bus: command
    commandbus:
        command:
            middleware:
                - tactician.middleware.locking
                - apisearch_server.middleware.repository_reference
                - apisearch_server.middleware.token
                - apisearch_server.middleware.plugins
                - apisearch_server.middleware.logs
                # - apisearch_server.middleware.interactions
                - apisearch_server.middleware.domain_events
                - tactician.middleware.command_handler

        query:
            middleware:
                - apisearch_server.middleware.repository_reference
                - apisearch_server.middleware.token
                - apisearch_server.middleware.plugins
                - apisearch_server.middleware.logs
                # - apisearch_server.middleware.interactions
                - apisearch_server.middleware.domain_events
                - tactician.middleware.command_handler