tactician:
    default_bus: command
    commandbus:
        command:
            middleware:
                - tactician.middleware.locking
                - apisearch.server.middleware.transaction
                # - apisearch.server.middleware.log_all_domain_events_to_elastica
                - apisearch.server.middleware.domain_events
                - tactician.middleware.command_handler

        query:
            middleware:
                - tactician.middleware.locking
                - apisearch.server.middleware.transaction
                # - apisearch.server.middleware.log_all_domain_events_to_elastica
                - apisearch.server.middleware.domain_events
                - tactician.middleware.command_handler