services:

    #
    # Middlewares
    #
    search_server.middleware.token_checker:
        class: Puntmig\Search\Server\Token\TokenChecker
        public: false
        arguments:
            - "%token_server_endpoint%"