services:

    #
    # Repositories
    #
    search_bundle.twig_extension:
        class: Mmoreram\SearchBundle\Twig\QueryExtension
        arguments:
            - "@search_bundle.url_builder"
        tags:
            - { name: twig.extension }
