sudo: required

services:
  - docker
language: php
php:
  - 7.1
  - 7.2

## Cache composer bits
cache:
  directories:
    - $HOME/.composer/cache/files

install:
  - composer install --no-interaction
  - composer dump-autoload

before_script:
  - docker-compose up --build -d
  - chmod +x docker/run-tests
  - chmod +x docker/print-logs

script:
  - docker exec -i -t $(docker ps -qf "name=apisearch_server") /var/www/apisearch/docker/run-tests

after_script:
  - docker exec -i -t $(docker ps -qf "name=apisearch_server") /var/www/apisearch/docker/print-logs
  - docker-compose down