bundles: Puntmig\Search\Server\PuntmigSearchServerBundle
routes:
    - "@PuntmigSearchServerBundle/Resources/config/routing.yml"
config:
    imports:
        - { resource: "@PuntmigSearchServerBundle/Resources/config/tactician.yml"}

    parameters:
        kernel.secret: nsdjkfhdsupoifjñksd
        token_server_endpoint: http://tokens.dev

    framework:
        form: false
        assets: false
        php_errors:
            log: true

    monolog:
        handlers:
            main:
                type: stream
                path: '%kernel.logs_dir%/%kernel.environment%.log'
                level: debug

    puntmig_search:
        repositories:
            search:
                http: false
                search:
                    repository_service: "search_server.elastica_repository"
                    in_memory: false
                event:
                    repository_service: "search_server.elastica_event_repository"
                    in_memory: false
            music_prod:
                endpoint: http://puntmig.net:8900
                app_id: music
                secret: 1cc7a3e0-bda5-11e7-abc4-cec278b6b50a
            music:
                endpoint: http://localhost:8999
                app_id: music
                secret: 5fadd8c4-c966-11e7-abc4-cec278b6b50a
