bundles: Apisearch\Server\ApisearchServerBundle
routes:
    - "@ApisearchServerBundle/Resources/config/routing.yml"
config:
    imports:
        - { resource: "@ApisearchServerBundle/Resources/config/tactician.yml"}

    parameters:
        kernel.secret: nsdjkfhdsupoifjñksd

    framework:
        form: false
        assets: false
        php_errors:
            log: true

    monolog:
        handlers:
            main:
                type: stream
                path: '%kernel.logs_dir%/%kernel.environment%.log'
                level: debug

    apisearch:
        repositories:
            search:
                http: false
                search:
                    repository_service: "apisearch.server.elastica_repository"
                    in_memory: false
                event:
                    repository_service: "apisearch.server.elastica_event_repository"
                    in_memory: false
                indexes:
                    - default
            music_prod:
                endpoint: http://api.apisear.ch
                app_id: music
                #
                # secret: 1cc7a3e0-bda5-11e7-abc4-cec278b6b50a
                # Uncomment this line to really make actions on production
                #
                token: 1cc7a3e0-bda5-11e7-abc4-cec278b6b50a
                indexes:
                    - default
            music_dev:
                endpoint: http://localhost:81
                app_id: music
                token: 5fadd8c4-c966-11e7-abc4-cec278b6b50a
                indexes:
                    - default
