bundles: Puntmig\Search\Server\PuntmigSearchServerBundle
routes:
    - "@PuntmigSearchServerBundle/Resources/config/routing.yml"
config:
    parameters:
        kernel.secret: jhaksjal
    framework:
        form: false
        assets: false
    monolog:
        handlers:
            main:
                type:     stream
                path:     '%kernel.logs_dir%/%kernel.environment%.log'
                level:    debug
                channels: ['!event']
                # formatter: search_bundle.log_formatter