bundles: Puntmig\Search\Server\PuntmigSearchServerBundle
routes:
    - "@PuntmigSearchServerBundle/Resources/config/routing.yml"
config:
    imports:
        - { resource: "@PuntmigSearchServerBundle/Resources/config/tactician.yml"}

    parameters:
        kernel.secret: nsdjkfhdsupoifjñksd
        token_server_endpoint: http://localhost:8120

    framework:
        form: false
        assets: false
        php_errors:
            log: true

    monolog:
        handlers:
            main:
                type: stream
                path: '%kernel.logs_dir%/%kernel.environment%.log'
                level: debug

    puntmig_search:
        repositories:
            search:
                http: false
                search:
                    repository_service: "search_server.elastica_repository"
                    in_memory: false
                event:
                    repository_service: "search_server.elastica_event_repository"
                    in_memory: false
