bundles: Apisearch\Server\ApisearchServerBundle
routes:
    - "@ApisearchServerBundle/Resources/config/routing.yml"
config:
    imports:
        - { resource: "@ApisearchServerBundle/Resources/config/tactician.yml"}

    parameters:
        kernel.secret: nsdjkfhdsupoifjñksd

    framework:
        form: false
        assets: false
        php_errors:
            log: true

    monolog:
        handlers:
            main:
                type: stream
                path: '%kernel.logs_dir%/%kernel.environment%.log'
                level: debug

    apisearch_server:
        cluster:
            localhost_9200:
                host: localhost
                port: 9200
            localhost_9201:
                host: localhost
                port: 9201
            localhost_9202:
                host: localhost
                port: 9202
            localhost_9203:
                host: localhost
                port: 9203
        config:
            repository:
                config_path: '/tmp/config_{app_id}_{index_id}'
                shards: 3
                replicas: 3
            event_repository:
                shards: 3
                replicas: 3
            log_repository:
                shards: 3
                replicas: 3

    apisearch:
        repositories:
            main:
                http: false
                search:
                    repository_service: "apisearch_server.elastica_repository"
                    in_memory: false
                event:
                    repository_service: "apisearch_server.elastica_event_repository"
                    in_memory: false
                log:
                    repository_service: "apisearch_server.elastica_log_repository"
                    in_memory: false
                indexes:
                    default: default
