bundles: Apisearch\Server\ApisearchServerBundle
routes:
    - "@ApisearchServerBundle/Resources/config/routing.yml"
config:
    imports:
        - { resource: "@ApisearchServerBundle/Resources/config/tactician.yml"}

    parameters:
        kernel.secret: nsdjkfhdsupoifjñksd

    framework:
        form: false
        assets: false
        php_errors:
            log: true

    monolog:
        handlers:
            main:
                type: stream
                path: '%kernel.logs_dir%/%kernel.environment%.log'
                level: debug

    apisearch_server:
        cluster:
            localhost_9200:
                host: localhost
                port: 9200
            localhost_9201:
                host: localhost
                port: 9201
            localhost_9202:
                host: localhost
                port: 9202
            localhost_9203:
                host: localhost
                port: 9203
        config:
            repository:
                config_path: '/tmp/config_{app_id}_{index_id}'
                shards: 4
                replicas: 4
            event_repository:
                shards: 4
                replicas: 4

    apisearch:
        repositories:
            search:
                http: false
                search:
                    repository_service: "apisearch_server.elastica_repository"
                    in_memory: false
                event:
                    repository_service: "apisearch_server.elastica_event_repository"
                    in_memory: false
                indexes:
                    default: default

            music_prod:
                endpoint: http://api.apisear.ch
                app_id: music
                #
                # secret: 1cc7a3e0-bda5-11e7-abc4-cec278b6b50a
                # Uncomment this line to really make actions on production
                #
                token: 64f64f7c-7ca6-46aa-8223-1051f8599f84
                indexes:
                    default: default

            music_dev:
                endpoint: http://localhost:81
                app_id: music
                token: 64f64f7c-7ca6-46aa-8223-1051f8599f84
                indexes:
                    default: default
