bundles: Apisearch\Server\ApisearchServerBundle
routes:
    - "@ApisearchServerBundle/Resources/config/routing.yml"
config:
    imports:
        - { resource: "@ApisearchServerBundle/Resources/config/tactician.yml"}
        - { resource: "@ApisearchServerBundle/app_deploy.yml", ignore_errors: true }

    parameters:
        kernel.secret: nsdjkfhdsupoifjñksd

    framework:
        form: false
        assets: false
        session:
            handler_id: null
        php_errors:
            log: true

    # config/services.yaml
    services:
        _defaults:
            autowire: false
            autoconfigure: false
            public: true

    monolog:
        handlers:
            main:
                type: stream
                path: '%kernel.logs_dir%/%kernel.environment%.log'
                level: debug

    #
    # Enable for Redis Cluster
    #
    # rs_queue:
    #     server:
    #         redis:
    #             cluster: true
    #             port: 6379
    #

    apisearch_server:
        god_token: "%env(APISEARCH_GOD_TOKEN)%"
        ping_token: "%env(APISEARCH_PING_TOKEN)%"

        #
        # Enable for Elasticsearch Cluster
        #
        # cluster:
        #    localhost_9200:
        #        host: localhost
        #        port: 9200
        #

        config:
            repository:
                config_path: '/tmp/config_{app_id}_{index_id}'
                shards: 1
                replicas: 0
            event_repository:
                shards: 1
                replicas: 0
            log_repository:
                shards: 1
                replicas: 0

    apisearch:
        repositories:
            main:
                adapter: service
                search:
                    repository_service: "apisearch_server.items_repository"
                app:
                    repository_service: "apisearch_server.app_repository"
                user:
                    repository_service: "apisearch_server.user_repository"
                event:
                    repository_service: "apisearch_server.events_repository"
                log:
                    repository_service: "apisearch_server.logs_repository"
                indexes:
                    default: default

            #
            # Enable for custom HTTP endpoint
            #
            # remote:
            #     adapter: http
            #     endpoint: __endpoint__
            #     app_id: __app_id__
            #     token: __token__
            #     indexes:
            #         default: __default_index__
            #
