version: '3.3'

services:
    elasticsearch:
        image: docker.elastic.co/elasticsearch/elasticsearch:6.2.4
        environment:
            - cluster.name=apisearch
            - http.host=0.0.0.0
            - transport.host=0.0.0.0
            - "ES_JAVA_OPTS=-Xms1g -Xmx1g"
            - action.auto_create_index=-apisearch*,+*
            - node.max_local_storage_nodes=10
        volumes:
            - esdata:/usr/share/elasticsearch/data
        ports:
            - 9200:9200

    redis:
        image: redis:4-alpine

    apisearch:
        build: ./docker/search-server

        depends_on:
            - elasticsearch
            - redis
        ports:
            - 8100:8100
        links:
            - redis

volumes:
    esdata:
        driver: local
